services:
  pomodoro-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: pomodoro-be:1.0.0
    container_name: pomodoro-be
    restart: unless-stopped
    ports:
      - "7000:7000"
    networks:
      - pomodoro-nw
    env_file:
      - .env
networks:
  pomodoro-nw:
    driver: bridge
