version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: pomodoro-be:1.0.0
    container_name: pomodoro-be
    restart: unless-stopped
    ports:
      - "7000:7000"
    networks:
      - network
    env_file:
      - .env

networks:
  network:
    driver: bridge
