services:
  pomodoro-be-reports-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: pomodoro-be-reports-svc:1.0.0
    container_name: pomodoro-be-reports-svc
    restart: unless-stopped
    ports:
      - "7070:7070"
    networks:
      - pomodoro-nw
    env_file:
      - .env
networks:
  pomodoro-nw:
    driver: bridge
